CREATE TABLE `tenantregistration` (
  `id` int(60) NOT NULL,
  `tenantfirstname` varchar(60) NOT NULL,
  `tenantlastnamae` varchar(60) NOT NULL,
  `tenantemailid` varchar(60) NOT NULL,
  `tenantejarinumber` varchar(60) NOT NULL,
  `tenantejariissuedate` varchar(60) NOT NULL,
  `tenantejariexpirydate` varchar(60) NOT NULL,
  `contractamount` varchar(60) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;